name: GitHub Action
on: [push]
jobs:
  hello-world:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      - run: pwd
      - run: ls -lah
      - run: cmake .
      - run: ls -lah
      - run: cmake --build .
      - run: ls -lah
      - run: ./hello_world
        if: "!startsWith(matrix.os, 'windows')"
      - run: ./Debug/hello_world.exe
        if: startsWith(matrix.os, 'windows')
