name: Native build
on: [push]
jobs:
  native-build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Cache vcpkg packages
        uses: actions/cache@v3
        with:
          key: vcpkg-deps-${{ hashFiles('vcpkg.json') }}
          path: ${{ runner.os == 'Windows' && 'C:\Users\runneradmin\AppData\Local\vcpkg\archives' || '~/.cache/vcpkg/archives' }}

      - run: cmake . --toolchain "$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"

      - run: cmake --build .

        # NOTE: on Windows, you must specify which configuration to test
        # https://gitlab.kitware.com/cmake/cmake/-/issues/20283
      - run: ctest ${{ runner.os == 'Windows' && '-C Debug' || '' }} 

